In [11]:
import pandas as pd

In [1]:
import pandas as pd
df = pd.read_csv('national-history.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      420 non-null    object
 1   death                     392 non-null    float64
 2   deathIncrease             420 non-null    int64
 3   inIcuCumulative           348 non-null    float64
 4   inIcuCurrently            347 non-null    float64
 5   hospitalizedIncrease      420 non-null    int64
 6   hospitalizedCurrently     356 non-null    float64
 7   hospitalizedCumulative    369 non-null    float64
 8   negative                  372 non-null    float64
 9   negativeIncrease          420 non-null    int64
 10  onVentilatorCumulative    341 non-null    float64
 11  onVentilatorCurrently     348 non-null    float64
 12  positive                  419 non-null    float64
 13  positiveIncrease          420 non-null    int64
 14  states                    420 non-null    int64
 15  totalTestResults          420 non-null    int64
 16  totalTestResultsIncrease  420 non-null    int64
dtypes: float64(9), int64(7), object(1)
memory usage: 55.9+ KB

In [6]:
mapeo = {
    'date': 'fecha',
    'death': 'muertes',
    'deathIncrease': 'aumento_muertes',
    'inIcuCumulative': 'enUCI_acumulado',
    'inIcuCurrently': 'enUCI_actual',
    'hospitalizedIncrease': 'aumento_hospitalizados',
    'hospitalizedCurrently': 'hospitalizados_actual',
    'hospitalizedCumulative': 'hospitalizados_acumulado',
    'negative': 'negativos',
    'negativeIncrease': 'aumento_negativos',
    'onVentilatorCumulative': 'enVentilador_acumulado',
    'onVentilatorCurrently': 'enVentilador_actual',
    'positive': 'positivos',
    'positiveIncrease': 'aumento_positivos',
    'states': 'estados',
    'totalTestResults': 'total_resultados_pruebas',
    'totalTestResultsIncrease': 'aumento_total_resultados_pruebas'
}
df = df.rename(columns=mapeo)

In [7]:
df

,fecha,muertes,aumento_muertes,enUCI_acumulado,enUCI_actual,aumento_hospitalizados,hospitalizados_actual,hospitalizados_acumulado,negativos,aumento_negativos,enVentilador_acumulado,enVentilador_actual,positivos,aumento_positivos,estados,total_resultados_pruebas,aumento_total_resultados_pruebas
0,2021-03-07,515151.0,842,45475.0,8134.0,726,40199.0,776361.0,74582825.0,131835,4281.0,2802.0,28756489.0,41835,56,363825123,1170059
1,2021-03-06,514309.0,1680,45453.0,8409.0,503,41401.0,775635.0,74450990.0,143835,4280.0,2811.0,28714654.0,60015,56,362655064,1430992
2,2021-03-05,512629.0,2221,45373.0,8634.0,2781,42541.0,775132.0,74307155.0,271917,4275.0,2889.0,28654639.0,68787,56,361224072,1744417
3,2021-03-04,510408.0,1743,45293.0,8970.0,1530,44172.0,772351.0,74035238.0,177957,4267.0,2973.0,28585852.0,65487,56,359479655,1590984
4,2021-03-03,508665.0,2449,45214.0,9359.0,2172,45462.0,770821.0,73857281.0,267001,4260.0,3094.0,28520365.0,66836,56,357888671,1406795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,2020-01-17,NaN,0,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,0.0,0,1,0,0
416,2020-01-16,NaN,0,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,0.0,0,1,0,0
417,2020-01-15,NaN,0,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,0.0,0,1,0,0
418,2020-01-14,NaN,0,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,0.0,0,1,0,0
419,2020-01-13,NaN,0,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,1,0,0

In [8]:
valores_nulos = df.isna()
valores_nulos

,fecha,muertes,aumento_muertes,enUCI_acumulado,enUCI_actual,aumento_hospitalizados,hospitalizados_actual,hospitalizados_acumulado,negativos,aumento_negativos,enVentilador_acumulado,enVentilador_actual,positivos,aumento_positivos,estados,total_resultados_pruebas,aumento_total_resultados_pruebas
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,False,True,False,True,True,False,True,True,True,False,True,True,False,False,False,False,False
416,False,True,False,True,True,False,True,True,True,False,True,True,False,False,False,False,False
417,False,True,False,True,True,False,True,True,True,False,True,True,False,False,False,False,False
418,False,True,False,True,True,False,True,True,True,False,True,True,False,False,False,False,False
419,False,True,False,True,True,False,True,True,True,False,True,True,True,False,False,False,False

In [9]:
cantidad_nulos_por_columna = valores_nulos.sum()
cantidad_nulos_por_columna

fecha                                0
muertes                             28
aumento_muertes                      0
enUCI_acumulado                     72
enUCI_actual                        73
aumento_hospitalizados               0
hospitalizados_actual               64
hospitalizados_acumulado            51
negativos                           48
aumento_negativos                    0
enVentilador_acumulado              79
enVentilador_actual                 72
positivos                            1
aumento_positivos                    0
estados                              0
total_resultados_pruebas             0
aumento_total_resultados_pruebas     0
dtype: int64

In [10]:
cantidad_total_nulos = cantidad_nulos_por_columna.sum()

In [11]:
cantidad_total_nulos

488

In [15]:
columnas_seleccionadas = ['fecha', 'positivos', 'aumento_positivos', 'estados']
nuevo_df = df.loc[:, columnas_seleccionadas]

In [16]:
nuevo_df

          fecha   positivos  aumento_positivos  estados
0    2021-03-07  28756489.0              41835       56
1    2021-03-06  28714654.0              60015       56
2    2021-03-05  28654639.0              68787       56
3    2021-03-04  28585852.0              65487       56
4    2021-03-03  28520365.0              66836       56
..          ...         ...                ...      ...
415  2020-01-17         0.0                  0        1
416  2020-01-16         0.0                  0        1
417  2020-01-15         0.0                  0        1
418  2020-01-14         0.0                  0        1
419  2020-01-13         NaN                  0        1

[420 rows x 4 columns]

In [17]:
 df.head(35)

,fecha,muertes,aumento_muertes,enUCI_acumulado,enUCI_actual,aumento_hospitalizados,hospitalizados_actual,hospitalizados_acumulado,negativos,aumento_negativos,enVentilador_acumulado,enVentilador_actual,positivos,aumento_positivos,estados,total_resultados_pruebas,aumento_total_resultados_pruebas
0,2021-03-07,515151.0,842,45475.0,8134.0,726,40199.0,776361.0,74582825.0,131835,4281.0,2802.0,28756489.0,41835,56,363825123,1170059
1,2021-03-06,514309.0,1680,45453.0,8409.0,503,41401.0,775635.0,74450990.0,143835,4280.0,2811.0,28714654.0,60015,56,362655064,1430992
2,2021-03-05,512629.0,2221,45373.0,8634.0,2781,42541.0,775132.0,74307155.0,271917,4275.0,2889.0,28654639.0,68787,56,361224072,1744417
3,2021-03-04,510408.0,1743,45293.0,8970.0,1530,44172.0,772351.0,74035238.0,177957,4267.0,2973.0,28585852.0,65487,56,359479655,1590984
4,2021-03-03,508665.0,2449,45214.0,9359.0,2172,45462.0,770821.0,73857281.0,267001,4260.0,3094.0,28520365.0,66836,56,357888671,1406795
5,2021-03-02,506216.0,1728,45084.0,9465.0,1871,46388.0,768649.0,73590280.0,255779,4257.0,3169.0,28453529.0,54248,56,356481876,1343519
6,2021-03-01,504488.0,1241,44956.0,9595.0,1024,46738.0,766778.0,73334501.0,118077,4252.0,3171.0,28399281.0,48092,56,355138357,1154440
7,2021-02-28,503247.0,1051,44907.0,9802.0,879,47352.0,765754.0,73216424.0,203599,4252.0,3245.0,28351189.0,54349,56,353983917,1408422
8,2021-02-27,502196.0,1847,44875.0,10114.0,1428,48871.0,764875.0,73012825.0,205090,4252.0,3335.0,28296840.0,71245,56,352575495,1655179
9,2021-02-26,500349.0,2141,44791.0,10466.0,1868,51112.0,763447.0,72807735.0,276829,4247.0,3466.0,28225595.0,74857,56,350920316,1803309
10,2021-02-25,498208.0,3138,44636.0,10846.0,2047,52669.0,761579.0,72530906.0,272209,4240.0,3567.0,28150738.0,75565,56,349117007,1826144
11,2021-02-24,495070.0,2447,44534.0,11026.0,2172,54118.0,759532.0,72258697.0,245318,4227.0,3685.0,28075173.0,73258,56,347290863,1450666
12,2021-02-23,492623.0,2241,44420.0,11272.0,2164,55058.0,757360.0,72013379.0,225267,4214.0,3755.0,28001915.0,69105,56,345840197,1193835
13,2021-02-22,490382.0,1235,44266.0,11536.0,1305,55403.0,755196.0,71788112.0,123611,4200.0,3804.0,27932810.0,52530,56,344646362,1201247
14,2021-02-21,489147.0,1287,44216.0,11862.0,997,56159.0,753891.0,71664501.0,156778,4197.0,3915.0,27880280.0,58702,56,343445115,1232995
15,2021-02-20,487860.0,2160,44166.0,12120.0,1732,58222.0,752894.0,71507723.0,141790,4197.0,3932.0,27821578.0,72354,56,342212120,1290481
16,2021-02-19,485700.0,2477,44085.0,12491.0,2674,59882.0,751162.0,71365933.0,224755,4187.0,4118.0,27749224.0,74676,56,340921639,1878033
17,2021-02-18,483223.0,2616,43964.0,13036.0,2497,62224.0,748488.0,71141178.0,218491,4178.0,4180.0,27674548.0,66824,56,339043606,1345849
18,2021-02-17,480607.0,2348,43823.0,13094.0,2857,63329.0,745991.0,70922687.0,233666,4154.0,4271.0,27607724.0,66839,56,337697757,1298421
19,2021-02-16,478259.0,1353,43673.0,13607.0,2094,64457.0,743134.0,70689021.0,101102,4149.0,4415.0,27540885.0,56312,56,336399336,1053698
20,2021-02-15,476906.0,1078,43553.0,13790.0,1130,65379.0,741040.0,70587919.0,143388,4143.0,4468.0,27484573.0,55077,56,335345638,1123560
21,2021-02-14,475828.0,1366,43516.0,14038.0,1236,66947.0,739910.0,70444531.0,171877,4141.0,4542.0,27429496.0,72164,56,334222078,1439631
22,2021-02-13,474462.0,3467,43463.0,14387.0,1805,69207.0,738674.0,70272654.0,234293,4140.0,4648.0,27357332.0,90642,56,332782447,1757608
23,2021-02-12,470995.0,5427,43389.0,14766.0,2347,71471.0,736869.0,70038361.0,255983,4126.0,4849.0,27266690.0,101030,56,331024839,1812454
24,2021-02-11,465568.0,3873,43291.0,15181.0,2460,74208.0,734522.0,69782378.0,260124,4113.0,4970.0,27165660.0,102417,56,329212385,1855929
25,2021-02-10,461695.0,3445,43184.0,15788.0,3226,76979.0,732062.0,69522254.0,155861,4106.0,5121.0,27063243.0,95194,56,327356456,1382709
26,2021-02-09,458250.0,2795,43000.0,16129.0,3144,79179.0,728836.0,69366393.0,337168,4092.0,5216.0,26968049.0,92986,56,325973747,1488481
27,2021-02-08,455455.0,1309,42833.0,16174.0,1638,80055.0,725692.0,69029225.0,142156,4080.0,5260.0,26875063.0,77737,56,324485266,1400009
28,2021-02-07,454146.0,1475,42779.0,16616.0,1543,81439.0,724054.0,68887069.0,208303,4079.0,5342.0,26797326.0,95994,56,323085257,1498808
29,2021-02-06,452671.0,2994,42730.0,17093.0,2443,84233.0,722511.0,68678766.0,282477,4078.0,5475.0,26701332.0,114557,56,321586449,1888854
30,2021-02-05,449677.0,3543,42626.0,17284.0,2940,86373.0,720068.0,68396289.0,270754,4060.0,5596.0,26586775.0,131146,56,319697595,1868496
31,2021-02-04,446134.0,5212,42472.0,17918.0,3402,88668.0,717128.0,68125535.0,217496,4059.0,5732.0,26455629.0,123907,56,317829099,1663995
32,2021-02-03,440922.0,3685,42323.0,18147.0,3975,91440.0,713726.0,67908039.0,224499,4044.0,5920.0,26331722.0,116960,56,316165104,1384881
33,2021-02-02,437237.0,3486,42148.0,18388.0,3285,92880.0,709751.0,67683540.0,167082,4035.0,6047.0,26214762.0,117616,56,314780223,1385595
34,2021-02-01,433751.0,1562,41998.0,18572.0,1766,93536.0,706466.0,67516458.0,344975,4025.0,6086.0,26097146.0,120200,56,313394628,1507545

In [18]:
nuevo_df.head(35)

         fecha   positivos  aumento_positivos  estados
0   2021-03-07  28756489.0              41835       56
1   2021-03-06  28714654.0              60015       56
2   2021-03-05  28654639.0              68787       56
3   2021-03-04  28585852.0              65487       56
4   2021-03-03  28520365.0              66836       56
5   2021-03-02  28453529.0              54248       56
6   2021-03-01  28399281.0              48092       56
7   2021-02-28  28351189.0              54349       56
8   2021-02-27  28296840.0              71245       56
9   2021-02-26  28225595.0              74857       56
10  2021-02-25  28150738.0              75565       56
11  2021-02-24  28075173.0              73258       56
12  2021-02-23  28001915.0              69105       56
13  2021-02-22  27932810.0              52530       56
14  2021-02-21  27880280.0              58702       56
15  2021-02-20  27821578.0              72354       56
16  2021-02-19  27749224.0              74676       56
17  2021-02-18  27674548.0              66824       56
18  2021-02-17  27607724.0              66839       56
19  2021-02-16  27540885.0              56312       56
20  2021-02-15  27484573.0              55077       56
21  2021-02-14  27429496.0              72164       56
22  2021-02-13  27357332.0              90642       56
23  2021-02-12  27266690.0             101030       56
24  2021-02-11  27165660.0             102417       56
25  2021-02-10  27063243.0              95194       56
26  2021-02-09  26968049.0              92986       56
27  2021-02-08  26875063.0              77737       56
28  2021-02-07  26797326.0              95994       56
29  2021-02-06  26701332.0             114557       56
30  2021-02-05  26586775.0             131146       56
31  2021-02-04  26455629.0             123907       56
32  2021-02-03  26331722.0             116960       56
33  2021-02-02  26214762.0             117616       56
34  2021-02-01  26097146.0             120200       56

Nuevo dataset

In [19]:
new_dataset = pd.read_csv('Fifa_world_cup_matches.csv')
new_dataset

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,ENGLAND,FRANCE,54%,36%,10%,1,2,10 DEC 2022,20 : 00,Quarter-final,...,1,0,9,15,0,0,49,54,193,308
60,ARGENTINA,CROATIA,34%,54%,12%,3,0,13 DEC 2022,20 : 00,Semi-final,...,1,0,12,10,0,0,85,63,321,260
61,FRANCE,MOROCCO,34%,55%,11%,2,0,14 DEC 2022,20 : 00,Semi-final,...,0,0,13,14,0,0,72,47,328,218
62,CROATIA,MOROCCO,45%,45%,10%,2,1,17 DEC 2022,16 : 00,Play-off for third place,...,0,0,7,14,0,0,75,72,288,277
63,ARGENTINA,FRANCE,46%,40%,14%,3,3,18 DEC 2022,16 : 00,Final,...,1,2,11,21,0,0,87,104,280,409

In [20]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 88 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   team1                                                  64 non-null     object
 1   team2                                                  64 non-null     object
 2   possession team1                                       64 non-null     object
 3   possession team2                                       64 non-null     object
 4   possession in contest                                  64 non-null     object
 5   number of goals team1                                  64 non-null     int64
 6   number of goals team2                                  64 non-null     int64
 7   date                                                   64 non-null     object
 8   hour                                                   64 non-null     object
 9   category                                               64 non-null     object
 10  total attempts team1                                   64 non-null     int64
 11  total attempts team2                                   64 non-null     int64
 12  conceded team1                                         64 non-null     int64
 13  conceded team2                                         64 non-null     int64
 14  goal inside the penalty area team1                     64 non-null     int64
 15  goal inside the penalty area team2                     64 non-null     int64
 16  goal outside the penalty area team1                    64 non-null     int64
 17  goal outside the penalty area team2                    64 non-null     int64
 18  assists team1                                          64 non-null     int64
 19  assists team2                                          64 non-null     int64
 20  on target attempts team1                               64 non-null     int64
 21  on target attempts team2                               64 non-null     int64
 22  off target attempts team1                              64 non-null     int64
 23  off target attempts team2                              64 non-null     int64
 24  attempts inside the penalty area team1                 64 non-null     int64
 25  attempts inside the penalty area  team2                64 non-null     int64
 26  attempts outside the penalty area  team1               64 non-null     int64
 27  attempts outside the penalty area  team2               64 non-null     int64
 28  left channel team1                                     64 non-null     int64
 29  left channel team2                                     64 non-null     int64
 30  left inside channel team1                              64 non-null     int64
 31  left inside channel team2                              64 non-null     int64
 32  central channel team1                                  64 non-null     int64
 33  central channel team2                                  64 non-null     int64
 34  right inside channel team1                             64 non-null     int64
 35  right inside channel team2                             64 non-null     int64
 36  right channel team1                                    64 non-null     int64
 37  right channel team2                                    64 non-null     int64
 38  total offers to receive team1                          64 non-null     int64
 39  total offers to receive team2                          64 non-null     int64
 40  inbehind offers to receive team1                       64 non-null     int64
 41  inbehind offers to receive team2                       64 non-null     int64
 42  inbetween offers to receive team1                      64 non-null     int64
 43  inbetween offers to receive team2                      64 non-null     int64
 44  infront offers to receive team1                        64 non-null     int64
 45  infront offers to receive team2                        64 non-null     int64
 46  receptions between midfield and defensive lines team1  64 non-null     int64
 47  receptions between midfield and defensive lines team2  64 non-null     int64
 48  attempted line breaks team1                            64 non-null     int64
 49  attempted line breaks team2                            64 non-null     int64
 50  completed line breaksteam1                             64 non-null     int64
 51  completed line breaks team2                            64 non-null     int64
 52  attempted defensive line breaks team1                  64 non-null     int64
 53  attempted defensive line breaks team2                  64 non-null     int64
 54  completed defensive line breaksteam1                   64 non-null     int64
 55  completed defensive line breaks team2                  64 non-null     int64
 56  yellow cards team1                                     64 non-null     int64
 57  yellow cards team2                                     64 non-null     int64
 58  red cards team1                                        64 non-null     int64
 59  red cards team2                                        64 non-null     int64
 60  fouls against team1                                    64 non-null     int64
 61  fouls against team2                                    64 non-null     int64
 62  offsides team1                                         64 non-null     int64
 63  offsides team2                                         64 non-null     int64
 64  passes team1                                           64 non-null     int64
 65  passes team2                                           64 non-null     int64
 66  passes completed team1                                 64 non-null     int64
 67  passes completed team2                                 64 non-null     int64
 68  crosses team1                                          64 non-null     int64
 69  crosses team2                                          64 non-null     int64
 70  crosses completed team1                                64 non-null     int64
 71  crosses completed team2                                64 non-null     int64
 72  switches of play completed team1                       64 non-null     int64
 73  switches of play completed team2                       64 non-null     int64
 74  corners team1                                          64 non-null     int64
 75  corners team2                                          64 non-null     int64
 76  free kicks team1                                       64 non-null     int64
 77  free kicks team2                                       64 non-null     int64
 78  penalties scored team1                                 64 non-null     int64
 79  penalties scored team2                                 64 non-null     int64
 80  goal preventions team1                                 64 non-null     int64
 81  goal preventions team2                                 64 non-null     int64
 82  own goals team1                                        64 non-null     int64
 83  own goals team2                                        64 non-null     int64
 84  forced turnovers team1                                 64 non-null     int64
 85  forced turnovers team2                                 64 non-null     int64
 86  defensive pressures applied team1                      64 non-null     int64
 87  defensive pressures applied team2                      64 non-null     int64
dtypes: int64(80), object(8)
memory usage: 44.1+ KB

In [45]:
matches = ['date','hour','team1','number of goals team1','number of goals team2','team2','category']
matches_df= new_dataset.loc[:, matches]

In [46]:
matches_df

,date,hour,team1,number of goals team1,number of goals team2,team2,category
0,20 NOV 2022,17 : 00,QATAR,0,2,ECUADOR,Group A
1,21 NOV 2022,14 : 00,ENGLAND,6,2,IRAN,Group B
2,21 NOV 2022,17 : 00,SENEGAL,0,2,NETHERLANDS,Group A
3,21 NOV 2022,20 : 00,UNITED STATES,1,1,WALES,Group B
4,22 NOV 2022,11 : 00,ARGENTINA,1,2,SAUDI ARABIA,Group C
...,...,...,...,...,...,...,...
59,10 DEC 2022,20 : 00,ENGLAND,1,2,FRANCE,Quarter-final
60,13 DEC 2022,20 : 00,ARGENTINA,3,0,CROATIA,Semi-final
61,14 DEC 2022,20 : 00,FRANCE,2,0,MOROCCO,Semi-final
62,17 DEC 2022,16 : 00,CROATIA,2,1,MOROCCO,Play-off for third place
63,18 DEC 2022,16 : 00,ARGENTINA,3,3,FRANCE,Final

In [47]:
grupos = new_dataset.groupby('category')
grupo_a = grupos.get_group('Group A')

In [48]:
grupo_a_filtrado= grupo_a[matches]

In [49]:
grupo_a_filtrado

,date,hour,team1,number of goals team1,number of goals team2,team2,category
0,20 NOV 2022,17 : 00,QATAR,0,2,ECUADOR,Group A
2,21 NOV 2022,17 : 00,SENEGAL,0,2,NETHERLANDS,Group A
17,25 NOV 2022,14 : 00,QATAR,1,3,SENEGAL,Group A
18,25 NOV 2022,17 : 00,NETHERLANDS,1,1,ECUADOR,Group A
32,29 NOV 2022,16 : 00,NETHERLANDS,2,0,QATAR,Group A
33,29 NOV 2022,16 : 00,ECUADOR,1,2,SENEGAL,Group A

In [67]:
for grupo, datos in grupos:
    matches_por_group = datos[matches]
    print("Grupo:", grupo)
    print(matches_por_group.to_string(index=False))
    print("\n")

Grupo: Final
       date    hour     team1  number of goals team1  number of goals team2  team2 category
18 DEC 2022 16 : 00 ARGENTINA                      3                      3 FRANCE    Final


Grupo: Group A
       date    hour       team1  number of goals team1  number of goals team2       team2 category
20 NOV 2022 17 : 00       QATAR                      0                      2     ECUADOR  Group A
21 NOV 2022 17 : 00     SENEGAL                      0                      2 NETHERLANDS  Group A
25 NOV 2022 14 : 00       QATAR                      1                      3     SENEGAL  Group A
25 NOV 2022 17 : 00 NETHERLANDS                      1                      1     ECUADOR  Group A
29 NOV 2022 16 : 00 NETHERLANDS                      2                      0       QATAR  Group A
29 NOV 2022 16 : 00     ECUADOR                      1                      2     SENEGAL  Group A


Grupo: Group B
       date    hour         team1  number of goals team1  number of goals team2         team2 category
21 NOV 2022 14 : 00       ENGLAND                      6                      2          IRAN  Group B
21 NOV 2022 20 : 00 UNITED STATES                      1                      1         WALES  Group B
25 NOV 2022 11 : 00         WALES                      0                      2          IRAN  Group B
25 NOV 2022 20 : 00       ENGLAND                      0                      0 UNITED STATES  Group B
29 NOV 2022 20 : 00         WALES                      0                      3       ENGLAND  Group B
29 NOV 2022 20 : 00          IRAN                      0                      1 UNITED STATES  Group B


Grupo: Group C
       date    hour        team1  number of goals team1  number of goals team2        team2 category
22 NOV 2022 11 : 00    ARGENTINA                      1                      2 SAUDI ARABIA  Group C
22 NOV 2022 17 : 00       MEXICO                      0                      0       POLAND  Group C
26 NOV 2022 14 : 00       POLAND                      2                      0 SAUDI ARABIA  Group C
26 NOV 2022 20 : 00    ARGENTINA                      2                      0       MEXICO  Group C
30 NOV 2022 20 : 00       POLAND                      0                      2    ARGENTINA  Group C
30 NOV 2022 20 : 00 SAUDI ARABIA                      1                      2       MEXICO  Group C


Grupo: Group D
       date    hour     team1  number of goals team1  number of goals team2     team2 category
22 NOV 2022 14 : 00   DENMARK                      0                      0   TUNISIA  Group D
22 NOV 2022 20 : 00    FRANCE                      4                      1 AUSTRALIA  Group D
26 NOV 2022 11 : 00   TUNISIA                      0                      1 AUSTRALIA  Group D
26 NOV 2022 17 : 00    FRANCE                      2                      1   DENMARK  Group D
30 NOV 2022 16 : 00 AUSTRALIA                      1                      0   DENMARK  Group D
30 NOV 2022 16 : 00   TUNISIA                      1                      0    FRANCE  Group D


Grupo: Group E
       date    hour      team1  number of goals team1  number of goals team2      team2 category
23 NOV 2022 14 : 00    GERMANY                      1                      2      JAPAN  Group E
23 NOV 2022 17 : 00      SPAIN                      7                      0 COSTA RICA  Group E
27 NOV 2022 11 : 00      JAPAN                      0                      1 COSTA RICA  Group E
27 NOV 2022 20 : 00      SPAIN                      1                      1    GERMANY  Group E
01 DEC 2022 20 : 00      JAPAN                      2                      1      SPAIN  Group E
01 DEC 2022 20 : 00 COSTA RICA                      2                      4    GERMANY  Group E


Grupo: Group F
       date    hour   team1  number of goals team1  number of goals team2   team2 category
23 NOV 2022 11 : 00 MOROCCO                      0                      0 CROATIA  Group F
23 NOV 2022 20 : 00 BELGIUM                      1                      0  CANADA  Group F
27 NOV 2022 14 : 00 BELGIUM                      0                      2 MOROCCO  Group F
27 NOV 2022 17 : 00 CROATIA                      4                      1  CANADA  Group F
01 DEC 2022 16 : 00 CROATIA                      0                      0 BELGIUM  Group F
01 DEC 2022 16 : 00  CANADA                      1                      2 MOROCCO  Group F


Grupo: Group G
       date    hour       team1  number of goals team1  number of goals team2       team2 category
24 NOV 2022 11 : 00 SWITZERLAND                      1                      0    CAMEROON  Group G
24 NOV 2022 20 : 00      BRAZIL                      2                      0      SERBIA  Group G
28 NOV 2022 11 : 00    CAMEROON                      3                      3      SERBIA  Group G
28 NOV 2022 17 : 00      BRAZIL                      1                      0 SWITZERLAND  Group G
02 DEC 2022 20 : 00      SERBIA                      2                      3 SWITZERLAND  Group G
02 DEC 2022 20 : 00    CAMEROON                      1                      0      BRAZIL  Group G


Grupo: Group H
       date    hour          team1  number of goals team1  number of goals team2          team2 category
24 NOV 2022 14 : 00        URUGUAY                      0                      0 KOREA REPUBLIC  Group H
24 NOV 2022 17 : 00       PORTUGAL                      3                      2          GHANA  Group H
28 NOV 2022 14 : 00 KOREA REPUBLIC                      2                      3          GHANA  Group H
28 NOV 2022 20 : 00       PORTUGAL                      2                      0        URUGUAY  Group H
02 DEC 2022 16 : 00          GHANA                      0                      2        URUGUAY  Group H
02 DEC 2022 16 : 00 KOREA REPUBLIC                      2                      1       PORTUGAL  Group H


Grupo: Play-off for third place
       date    hour   team1  number of goals team1  number of goals team2   team2                 category
17 DEC 2022 16 : 00 CROATIA                      2                      1 MOROCCO Play-off for third place


Grupo: Quarter-final
       date    hour       team1  number of goals team1  number of goals team2     team2      category
09 DEC 2022 16 : 00     CROATIA                      1                      1    BRAZIL Quarter-final
09 DEC 2022 20 : 00 NETHERLANDS                      2                      2 ARGENTINA Quarter-final
10 DEC 2022 16 : 00     MOROCCO                      1                      0  PORTUGAL Quarter-final
10 DEC 2022 20 : 00     ENGLAND                      1                      2    FRANCE Quarter-final


Grupo: Round of 16
       date    hour       team1  number of goals team1  number of goals team2          team2    category
03 DEC 2022 16 : 00 NETHERLANDS                      3                      1  UNITED STATES Round of 16
03 DEC 2022 20 : 00   ARGENTINA                      2                      1      AUSTRALIA Round of 16
04 DEC 2022 16 : 00      FRANCE                      3                      1         POLAND Round of 16
04 DEC 2022 20 : 00     ENGLAND                      3                      0        SENEGAL Round of 16
05 DEC 2022 16 : 00       JAPAN                      1                      1        CROATIA Round of 16
05 DEC 2022 20 : 00      BRAZIL                      4                      1 KOREA REPUBLIC Round of 16
06 DEC 2022 16 : 00     MOROCCO                      0                      0          SPAIN Round of 16
06 DEC 2022 20 : 00    PORTUGAL                      6                      1    SWITZERLAND Round of 16


Grupo: Semi-final
       date    hour     team1  number of goals team1  number of goals team2   team2   category
13 DEC 2022 20 : 00 ARGENTINA                      3                      0 CROATIA Semi-final
14 DEC 2022 20 : 00    FRANCE                      2                      0 MOROCCO Semi-final

In [68]:
for grupo, datos in grupos:
    if "Group" in grupo:
        matches_por_group = datos[matches]
        print("Grupo:", grupo)
        print(matches_por_group.to_string(index=False))
        print("\n")

Grupo: Group A
       date    hour       team1  number of goals team1  number of goals team2       team2 category
20 NOV 2022 17 : 00       QATAR                      0                      2     ECUADOR  Group A
21 NOV 2022 17 : 00     SENEGAL                      0                      2 NETHERLANDS  Group A
25 NOV 2022 14 : 00       QATAR                      1                      3     SENEGAL  Group A
25 NOV 2022 17 : 00 NETHERLANDS                      1                      1     ECUADOR  Group A
29 NOV 2022 16 : 00 NETHERLANDS                      2                      0       QATAR  Group A
29 NOV 2022 16 : 00     ECUADOR                      1                      2     SENEGAL  Group A


Grupo: Group B
       date    hour         team1  number of goals team1  number of goals team2         team2 category
21 NOV 2022 14 : 00       ENGLAND                      6                      2          IRAN  Group B
21 NOV 2022 20 : 00 UNITED STATES                      1                      1         WALES  Group B
25 NOV 2022 11 : 00         WALES                      0                      2          IRAN  Group B
25 NOV 2022 20 : 00       ENGLAND                      0                      0 UNITED STATES  Group B
29 NOV 2022 20 : 00         WALES                      0                      3       ENGLAND  Group B
29 NOV 2022 20 : 00          IRAN                      0                      1 UNITED STATES  Group B


Grupo: Group C
       date    hour        team1  number of goals team1  number of goals team2        team2 category
22 NOV 2022 11 : 00    ARGENTINA                      1                      2 SAUDI ARABIA  Group C
22 NOV 2022 17 : 00       MEXICO                      0                      0       POLAND  Group C
26 NOV 2022 14 : 00       POLAND                      2                      0 SAUDI ARABIA  Group C
26 NOV 2022 20 : 00    ARGENTINA                      2                      0       MEXICO  Group C
30 NOV 2022 20 : 00       POLAND                      0                      2    ARGENTINA  Group C
30 NOV 2022 20 : 00 SAUDI ARABIA                      1                      2       MEXICO  Group C


Grupo: Group D
       date    hour     team1  number of goals team1  number of goals team2     team2 category
22 NOV 2022 14 : 00   DENMARK                      0                      0   TUNISIA  Group D
22 NOV 2022 20 : 00    FRANCE                      4                      1 AUSTRALIA  Group D
26 NOV 2022 11 : 00   TUNISIA                      0                      1 AUSTRALIA  Group D
26 NOV 2022 17 : 00    FRANCE                      2                      1   DENMARK  Group D
30 NOV 2022 16 : 00 AUSTRALIA                      1                      0   DENMARK  Group D
30 NOV 2022 16 : 00   TUNISIA                      1                      0    FRANCE  Group D


Grupo: Group E
       date    hour      team1  number of goals team1  number of goals team2      team2 category
23 NOV 2022 14 : 00    GERMANY                      1                      2      JAPAN  Group E
23 NOV 2022 17 : 00      SPAIN                      7                      0 COSTA RICA  Group E
27 NOV 2022 11 : 00      JAPAN                      0                      1 COSTA RICA  Group E
27 NOV 2022 20 : 00      SPAIN                      1                      1    GERMANY  Group E
01 DEC 2022 20 : 00      JAPAN                      2                      1      SPAIN  Group E
01 DEC 2022 20 : 00 COSTA RICA                      2                      4    GERMANY  Group E


Grupo: Group F
       date    hour   team1  number of goals team1  number of goals team2   team2 category
23 NOV 2022 11 : 00 MOROCCO                      0                      0 CROATIA  Group F
23 NOV 2022 20 : 00 BELGIUM                      1                      0  CANADA  Group F
27 NOV 2022 14 : 00 BELGIUM                      0                      2 MOROCCO  Group F
27 NOV 2022 17 : 00 CROATIA                      4                      1  CANADA  Group F
01 DEC 2022 16 : 00 CROATIA                      0                      0 BELGIUM  Group F
01 DEC 2022 16 : 00  CANADA                      1                      2 MOROCCO  Group F


Grupo: Group G
       date    hour       team1  number of goals team1  number of goals team2       team2 category
24 NOV 2022 11 : 00 SWITZERLAND                      1                      0    CAMEROON  Group G
24 NOV 2022 20 : 00      BRAZIL                      2                      0      SERBIA  Group G
28 NOV 2022 11 : 00    CAMEROON                      3                      3      SERBIA  Group G
28 NOV 2022 17 : 00      BRAZIL                      1                      0 SWITZERLAND  Group G
02 DEC 2022 20 : 00      SERBIA                      2                      3 SWITZERLAND  Group G
02 DEC 2022 20 : 00    CAMEROON                      1                      0      BRAZIL  Group G


Grupo: Group H
       date    hour          team1  number of goals team1  number of goals team2          team2 category
24 NOV 2022 14 : 00        URUGUAY                      0                      0 KOREA REPUBLIC  Group H
24 NOV 2022 17 : 00       PORTUGAL                      3                      2          GHANA  Group H
28 NOV 2022 14 : 00 KOREA REPUBLIC                      2                      3          GHANA  Group H
28 NOV 2022 20 : 00       PORTUGAL                      2                      0        URUGUAY  Group H
02 DEC 2022 16 : 00          GHANA                      0                      2        URUGUAY  Group H
02 DEC 2022 16 : 00 KOREA REPUBLIC                      2                      1       PORTUGAL  Group H

In [70]:
new_dataset['category'].unique()

array(['Group A', 'Group B', 'Group C', 'Group D', 'Group F', 'Group E',
       'Group G', 'Group H', 'Round of 16', 'Quarter-final', 'Semi-final',
       'Play-off for third place', 'Final'], dtype=object)

In [71]:
eliminacion_directa = {
    'Round of 16' : 'Octavos de Final', 
    'Quarter-final': ' Cuartos de Final', 
    'Semi-final': 'Semifinal',
    'Play-off for third place': 'Tercer Puesto', 
    'Final': 'Final'
}
new_dataset['category'] = new_dataset['category'].replace(eliminacion_directa)

In [72]:
new_dataset

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,ENGLAND,FRANCE,54%,36%,10%,1,2,10 DEC 2022,20 : 00,Cuartos de Final,...,1,0,9,15,0,0,49,54,193,308
60,ARGENTINA,CROATIA,34%,54%,12%,3,0,13 DEC 2022,20 : 00,Semifinal,...,1,0,12,10,0,0,85,63,321,260
61,FRANCE,MOROCCO,34%,55%,11%,2,0,14 DEC 2022,20 : 00,Semifinal,...,0,0,13,14,0,0,72,47,328,218
62,CROATIA,MOROCCO,45%,45%,10%,2,1,17 DEC 2022,16 : 00,Tercer Puesto,...,0,0,7,14,0,0,75,72,288,277
63,ARGENTINA,FRANCE,46%,40%,14%,3,3,18 DEC 2022,16 : 00,Final,...,1,2,11,21,0,0,87,104,280,409

In [74]:
eliminacion = ['Octavos de Final',' Cuartos de Final','Semifinal','Tercer Puesto','Final']
filtrado = new_dataset[new_dataset['category'].isin(eliminacion)]

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
48,NETHERLANDS,UNITED STATES,33%,54%,13%,3,1,03 DEC 2022,16 : 00,Octavos de Final,...,0,0,18,13,0,0,101,77,325,256
49,ARGENTINA,AUSTRALIA,53%,35%,12%,2,1,03 DEC 2022,20 : 00,Octavos de Final,...,0,0,5,14,1,0,67,73,240,453
50,FRANCE,POLAND,48%,42%,10%,3,1,04 DEC 2022,16 : 00,Octavos de Final,...,0,1,11,16,0,0,71,64,220,297
51,ENGLAND,SENEGAL,54%,35%,11%,3,0,04 DEC 2022,20 : 00,Octavos de Final,...,0,0,10,8,0,0,60,74,230,339
52,JAPAN,CROATIA,35%,51%,14%,1,1,05 DEC 2022,16 : 00,Octavos de Final,...,0,0,18,11,0,0,100,100,405,308
53,BRAZIL,KOREA REPUBLIC,47%,44%,9%,4,1,05 DEC 2022,20 : 00,Octavos de Final,...,1,0,10,18,0,0,73,81,310,329
54,MOROCCO,SPAIN,22%,68%,10%,0,0,06 DEC 2022,16 : 00,Octavos de Final,...,0,0,14,6,0,0,100,66,573,217
55,PORTUGAL,SWITZERLAND,43%,48%,9%,6,1,06 DEC 2022,20 : 00,Octavos de Final,...,0,0,10,15,0,0,71,54,357,240
56,CROATIA,BRAZIL,45%,45%,10%,1,1,09 DEC 2022,16 : 00,Cuartos de Final,...,0,0,21,9,0,0,95,77,365,423
57,NETHERLANDS,ARGENTINA,45%,44%,11%,2,2,09 DEC 2022,20 : 00,Cuartos de Final,...,0,1,15,5,0,0,91,79,401,323
58,MOROCCO,PORTUGAL,22%,65%,13%,1,0,10 DEC 2022,16 : 00,Cuartos de Final,...,0,0,11,10,0,0,88,44,373,165
59,ENGLAND,FRANCE,54%,36%,10%,1,2,10 DEC 2022,20 : 00,Cuartos de Final,...,1,0,9,15,0,0,49,54,193,308
60,ARGENTINA,CROATIA,34%,54%,12%,3,0,13 DEC 2022,20 : 00,Semifinal,...,1,0,12,10,0,0,85,63,321,260
61,FRANCE,MOROCCO,34%,55%,11%,2,0,14 DEC 2022,20 : 00,Semifinal,...,0,0,13,14,0,0,72,47,328,218
62,CROATIA,MOROCCO,45%,45%,10%,2,1,17 DEC 2022,16 : 00,Tercer Puesto,...,0,0,7,14,0,0,75,72,288,277
63,ARGENTINA,FRANCE,46%,40%,14%,3,3,18 DEC 2022,16 : 00,Final,...,1,2,11,21,0,0,87,104,280,409

NEW DATASET

In [33]:
dataset_3 = pd.read_csv('players_15.csv')
dataset_3

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15460,220806,https://sofifa.com/player/220806/ellis-redman/...,E. Redman,Ellis Redman,17,1996-09-26,187,81,Wales,Newport County,...,37+0,38+0,38+0,38+0,37+0,40+0,41+0,41+0,41+0,40+0
15461,225509,https://sofifa.com/player/225509/aaron-collins...,A. Collins,Aaron Collins,17,1997-06-01,178,57,Wales,Newport County,...,31+0,30+0,30+0,30+0,31+0,32+0,31+0,31+0,31+0,32+0
15462,217591,https://sofifa.com/player/217591/piotr-zemlo/1...,P. Żemło,Piotr Żemło,18,1995-07-10,190,76,Poland,Wisła Kraków,...,48+0,46+0,46+0,46+0,48+0,51+0,53+0,53+0,53+0,51+0
15463,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,...,37+0,36+0,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0
15464,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,36+0,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0

In [34]:
nulos =dataset_3.isna()
nulos

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15460,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15461,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15462,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15463,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15464,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [35]:
cantidad_nulos_por_columna2 = nulos.sum()
cantidad_nulos_por_columna2

sofifa_id        0
player_url       0
short_name       0
long_name        0
age              0
              ...
lb            1703
lcb           1703
cb            1703
rcb           1703
rb            1703
Length: 104, dtype: int64

In [42]:
dataset_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15465 entries, 0 to 15464
Columns: 104 entries, sofifa_id to rb
dtypes: float64(17), int64(11), object(76)
memory usage: 12.3+ MB

In [43]:
nombres_columnas =dataset_3.columns
nombres_columnas

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=104)

In [44]:
dataset_3

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15460,220806,https://sofifa.com/player/220806/ellis-redman/...,E. Redman,Ellis Redman,17,1996-09-26,187,81,Wales,Newport County,...,37+0,38+0,38+0,38+0,37+0,40+0,41+0,41+0,41+0,40+0
15461,225509,https://sofifa.com/player/225509/aaron-collins...,A. Collins,Aaron Collins,17,1997-06-01,178,57,Wales,Newport County,...,31+0,30+0,30+0,30+0,31+0,32+0,31+0,31+0,31+0,32+0
15462,217591,https://sofifa.com/player/217591/piotr-zemlo/1...,P. Żemło,Piotr Żemło,18,1995-07-10,190,76,Poland,Wisła Kraków,...,48+0,46+0,46+0,46+0,48+0,51+0,53+0,53+0,53+0,51+0
15463,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,...,37+0,36+0,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0
15464,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,36+0,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0

In [45]:
dataset_3.head(50)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,176580,https://sofifa.com/player/176580/luis-suarez/1...,L. Suárez,Luis Alberto Suárez Díaz,27,1987-01-24,181,81,Uruguay,FC Barcelona,...,67+3,67+3,67+3,67+3,67+3,62+3,57+3,57+3,57+3,62+3
6,183277,https://sofifa.com/player/183277/eden-hazard/1...,E. Hazard,Eden Hazard,23,1991-01-07,173,74,Belgium,Chelsea,...,62+2,64+2,64+2,64+2,62+2,54+2,46+2,46+2,46+2,54+2
7,7826,https://sofifa.com/player/7826/robin-van-persi...,R. van Persie,Robin van Persie,30,1983-08-06,187,71,Netherlands,Manchester United,...,60+3,63+3,63+3,63+3,60+3,54+3,48+3,48+3,48+3,54+3
8,121944,https://sofifa.com/player/121944/bastian-schwe...,B. Schweinsteiger,Bastian Schweinsteiger,29,1984-08-01,183,79,Germany,FC Bayern München,...,81+2,84+2,84+2,84+2,81+2,81+2,79+2,79+2,79+2,81+2
9,156616,https://sofifa.com/player/156616/franck-ribery...,F. Ribéry,Franck Bilal Ribéry,31,1983-04-07,170,72,France,FC Bayern München,...,63+2,63+2,63+2,63+2,63+2,53+2,44+2,44+2,44+2,53+2
10,167397,https://sofifa.com/player/167397/radamel-falca...,Falcao,Radamel Falcao García Zárate,28,1986-02-10,177,72,Colombia,Manchester United,...,58+2,60+2,60+2,60+2,58+2,56+2,55+2,55+2,55+2,56+2
11,173731,https://sofifa.com/player/173731/gareth-bale/1...,G. Bale,Gareth Frank Bale,24,1989-07-16,183,74,Wales,Real Madrid,...,76+2,75+2,75+2,75+2,76+2,74+2,70+2,70+2,70+2,74+2
12,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,25,1988-08-21,184,78,Poland,FC Bayern München,...,61+2,65+2,65+2,65+2,61+2,58+2,56+2,56+2,56+2,58+2
13,121939,https://sofifa.com/player/121939/philipp-lahm/...,P. Lahm,Philipp Lahm,30,1983-11-11,170,66,Germany,FC Bayern München,...,88+2,85+2,85+2,85+2,88+2,85+2,81+2,81+2,81+2,85+2
14,155862,https://sofifa.com/player/155862/sergio-ramos-...,Sergio Ramos,Sergio Ramos García,28,1986-03-30,183,75,Spain,Real Madrid,...,81+2,80+2,80+2,80+2,81+2,84+2,85+2,85+2,85+2,84+2
15,164240,https://sofifa.com/player/164240/thiago-emilia...,Thiago Silva,Thiago Emiliano da Silva,29,1984-09-22,183,79,Brazil,Paris Saint-Germain,...,81+2,82+2,82+2,82+2,81+2,83+2,85+2,85+2,85+2,83+2
16,168542,https://sofifa.com/player/168542/david-josue-j...,David Silva,David Josué Jiménez Silva,28,1986-01-08,170,67,Spain,Manchester City,...,63+2,64+2,64+2,64+2,63+2,54+2,47+2,47+2,47+2,54+2
17,177003,https://sofifa.com/player/177003/luka-modric/1...,L. Modrić,Luka Modrić,28,1985-09-09,174,65,Croatia,Real Madrid,...,81+2,80+2,80+2,80+2,81+2,76+2,72+2,72+2,72+2,76+2
18,198710,https://sofifa.com/player/198710/james-rodrigu...,J. Rodríguez,James David Rodríguez Rubio,22,1991-07-12,180,75,Colombia,Real Madrid,...,64+2,68+2,68+2,68+2,64+2,59+2,53+2,53+2,53+2,59+2
19,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar,Neymar da Silva Santos Junior,22,1992-02-05,175,64,Brazil,FC Barcelona,...,61+3,59+3,59+3,59+3,61+3,55+3,45+3,45+3,45+3,55+3
20,192119,https://sofifa.com/player/192119/thibaut-court...,T. Courtois,Thibaut Courtois,22,1992-05-11,199,88,Belgium,Chelsea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,178603,https://sofifa.com/player/178603/mats-hummels/...,M. Hummels,Mats Hummels,25,1988-12-16,192,90,Germany,Borussia Dortmund,...,79+2,82+2,82+2,82+2,79+2,81+2,84+2,84+2,84+2,81+2
22,183898,https://sofifa.com/player/183898/angel-di-mari...,A. Di María,Ángel Fabián Di María Hernández,26,1988-02-14,180,70,Argentina,Manchester United,...,75+2,73+2,73+2,73+2,75+2,70+2,64+2,64+2,64+2,70+2
23,188350,https://sofifa.com/player/188350/marco-reus/15...,M. Reus,Marco Reus,25,1989-05-31,181,73,Germany,Borussia Dortmund,...,64+1,63+1,63+1,63+1,64+1,56+1,48+1,48+1,48+1,56+1
24,189596,https://sofifa.com/player/189596/thomas-muller...,T. Müller,Thomas Müller,24,1989-09-13,186,75,Germany,FC Bayern München,...,68+2,69+2,69+2,69+2,68+2,65+2,58+2,58+2,58+2,65+2
25,153079,https://sofifa.com/player/153079/sergio-aguero...,S. Agüero,Sergio Leonel Agüero del Castillo,26,1988-06-02,172,74,Argentina,Manchester City,...,58+2,59+2,59+2,59+2,58+2,51+2,47+2,47+2,47+2,51+2
26,176635,https://sofifa.com/player/176635/mesut-ozil/15...,M. Özil,Mesut Özil,25,1988-10-15,183,76,Germany,Arsenal,...,59+1,62+1,62+1,62+1,59+1,51+1,44+1,44+1,44+1,51+1
27,10535,https://sofifa.com/player/10535/xavier-hernand...,Xavi,Xavier Hernández Creus,34,1980-01-25,170,68,Spain,FC Barcelona,...,75+2,77+2,77+2,77+2,75+2,69+2,63+2,63+2,63+2,69+2
28,20289,https://sofifa.com/player/20289/yaya-toure/15/...,Y. Touré,Gnégnéri Yaya Touré,31,1983-05-13,189,90,Ivory Coast,Manchester City,...,81+2,84+2,84+2,84+2,81+2,81+2,82+2,82+2,82+2,81+2
29,54050,https://sofifa.com/player/54050/wayne-rooney/1...,W. Rooney,Wayne Mark Rooney,28,1985-10-24,176,83,England,Manchester United,...,65+2,69+2,69+2,69+2,65+2,63+2,60+2,60+2,60+2,63+2
30,139720,https://sofifa.com/player/139720/vincent-kompa...,V. Kompany,Vincent Kompany,28,1986-04-10,192,85,Belgium,Manchester City,...,78+2,80+2,80+2,80+2,78+2,81+2,84+2,84+2,84+2,81+2
31,192318,https://sofifa.com/player/192318/mario-gotze/1...,M. Götze,Mario Götze,22,1992-06-03,176,72,Germany,FC Bayern München,...,63+1,65+1,65+1,65+1,63+1,55+1,48+1,48+1,48+1,55+1
32,189511,https://sofifa.com/player/189511/sergio-busque...,Sergio Busquets,Sergio Busquets i Burgos,25,1988-07-16,189,73,Spain,FC Barcelona,...,79+2,83+2,83+2,83+2,79+2,79+2,80+2,80+2,80+2,79+2
33,182521,https://sofifa.com/player/182521/toni-kroos/15...,T. Kroos,Toni Kroos,24,1990-01-04,182,78,Germany,Real Madrid,...,74+2,76+2,76+2,76+2,74+2,68+2,63+2,63+2,63+2,68+2
34,165153,https://sofifa.com/player/165153/karim-benzema...,K. Benzema,Karim Benzema,26,1987-12-19,184,79,France,Real Madrid,...,58+2,58+2,58+2,58+2,58+2,53+2,49+2,49+2,49+2,53+2
35,179813,https://sofifa.com/player/179813/edinson-cavan...,E. Cavani,Edinson Roberto Cavani Gómez,27,1987-02-14,184,71,Uruguay,Paris Saint-Germain,...,63+2,63+2,63+2,63+2,63+2,60+2,56+2,56+2,56+2,60+2
36,179844,https://sofifa.com/player/179844/diego-da-silv...,Diego Costa,Diego da Silva Costa,25,1988-10-07,188,81,Spain,Chelsea,...,60+1,62+1,62+1,62+1,60+1,59+1,57+1,57+1,57+1,59+1
37,181872,https://sofifa.com/player/181872/arturo-vidal/...,A. Vidal,Arturo Vidal,27,1987-05-22,180,75,Chile,Juventus,...,83+2,83+2,83+2,83+2,83+2,83+2,82+2,82+2,82+2,83+2
38,167948,https://sofifa.com/player/167948/hugo-lloris/1...,H. Lloris,Hugo Lloris,27,1986-12-26,188,78,France,Tottenham Hotspur,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,177610,https://sofifa.com/player/177610/javier-martin...,Javi Martinez,Javier Martínez Aginaga,25,1988-09-02,190,81,Spain,FC Bayern München,...,77+1,82+1,82+1,82+1,77+1,81+1,84+1,84+1,84+1,81+1
40,178088,https://sofifa.com/player/178088/juan-manuel-m...,Juan Mata,Juan Manuel Mata García,26,1988-04-28,174,63,Spain,Manchester United,...,61+1,63+1,63+1,63+1,61+1,54+1,46+1,46+1,46+1,54+1
41,183907,https://sofifa.com/player/183907/jerome-boaten...,J. Boateng,Jérôme Boateng,25,1988-09-03,192,90,Germany,FC Bayern München,...,78+2,77+2,77+2,77+2,78+2,80+2,83+2,83+2,83+2,80+2
42,48940,https://sofifa.com/player/48940/petr-cech/15/1...,P. Čech,Petr Čech,32,1982-05-20,196,90,Czech Republic,Chelsea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,143001,https://sofifa.com/player/143001/carlos-tevez/...,C. Tévez,Carlos Alberto Tevez,30,1984-02-05,173,75,Argentina,Juventus,...,69+1,69+1,69+1,69+1,69+1,65+1,62+1,62+1,62+1,65+1
44,152729,https://sofifa.com/player/152729/gerard-pique-...,Piqué,Gerard Piqué Bernabéu,27,1987-02-02,192,85,Spain,FC Barcelona,...,75+2,81+2,81+2,81+2,75+2,79+2,82+2,82+2,82+2,79+2
45,143745,https://sofifa.com/player/143745/arda-turan/15...,A. Turan,Arda Turan,27,1987-01-30,177,76,Turkey,Atlético Madrid,...,74+1,73+1,73+1,73+1,74+1,70+1,69+1,69+1,69+1,70+1
46,184941,https://sofifa.com/player/184941/alexis-sanche...,A. Sánchez,Alexis Alejandro Sánchez Sánchez,25,1988-12-19,171,62,Chile,Arsenal,...,63+1,63+1,63+1,63+1,63+1,58+1,51+1,51+1,51+1,58+1
47,188152,https://sofifa.com/player/188152/oscar-dos-san...,Oscar,Oscar dos Santos Emboaba Júnior,22,1991-09-09,179,67,Brazil,Chelsea,...,65+1,63+1,63+1,63+1,65+1,58+1,49+1,49+1,49+1,58+1
48,165239,https://sofifa.com/player/165239/samir-nasri/1...,S. Nasri,Samir Nasri,27,1987-06-26,175,75,France,Manchester City,...,65+1,64+1,64+1,64+1,65+1,57+1,50+1,50+1,50+1,57+1
49,177509,https://sofifa.com/player/177509/mehdi-benatia...,M. Benatia,Medhi Amine El Mouttaqi Benatia,27,1987-04-17,188,88,Morocco,FC Bayern München,...,75+0,76+0,76+0,76+0,75+0,80+0,84+0,84+0,84+0,80+0

In [49]:
columna = 'nationality'
valor_buscado = 'Argentina'
jugadores_argentinos = dataset_3[dataset_3[columna] == valor_buscado]
jugadores_argentinos.head(50)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
22,183898,https://sofifa.com/player/183898/angel-di-mari...,A. Di María,Ángel Fabián Di María Hernández,26,1988-02-14,180,70,Argentina,Manchester United,...,75+2,73+2,73+2,73+2,75+2,70+2,64+2,64+2,64+2,70+2
25,153079,https://sofifa.com/player/153079/sergio-aguero...,S. Agüero,Sergio Leonel Agüero del Castillo,26,1988-06-02,172,74,Argentina,Manchester City,...,58+2,59+2,59+2,59+2,58+2,51+2,47+2,47+2,47+2,51+2
43,143001,https://sofifa.com/player/143001/carlos-tevez/...,C. Tévez,Carlos Alberto Tevez,30,1984-02-05,173,75,Argentina,Juventus,...,69+1,69+1,69+1,69+1,69+1,65+1,62+1,62+1,62+1,65+1
51,167664,https://sofifa.com/player/167664/gonzalo-higua...,G. Higuaín,Gonzalo Gerardo Higuaín,26,1987-12-10,184,82,Argentina,Napoli,...,56+1,55+1,55+1,55+1,56+1,51+1,48+1,48+1,48+1,51+1
72,170481,https://sofifa.com/player/170481/ezequiel-gara...,E. Garay,Ezequiel Marcelo Garay,27,1986-10-10,188,80,Argentina,Zenit St. Petersburg,...,74+1,77+1,77+1,77+1,74+1,77+1,82+1,82+1,82+1,77+1
84,142754,https://sofifa.com/player/142754/javier-masche...,J. Mascherano,Javier Alejandro Mascherano,30,1984-06-08,174,74,Argentina,FC Barcelona,...,80+1,82+1,82+1,82+1,80+1,82+1,82+1,82+1,82+1,82+1
121,184144,https://sofifa.com/player/184144/nicolas-gaita...,N. Gaitán,Osvaldo Nicolás Fabián Gaitán,26,1988-02-23,173,67,Argentina,SL Benfica,...,63+0,63+0,63+0,63+0,63+0,56+0,49+0,49+0,49+0,56+0
136,142784,https://sofifa.com/player/142784/pablo-zabalet...,P. Zabaleta,Pablo Javier Zabaleta Girod,29,1985-01-16,178,76,Argentina,Manchester City,...,80+1,80+1,80+1,80+1,80+1,81+1,82+1,82+1,82+1,81+1
139,152999,https://sofifa.com/player/152999/rodrigo-palac...,R. Palacio,Rodrigo Sebastián Palacio,32,1982-02-05,175,70,Argentina,Inter,...,58+0,58+0,58+0,58+0,58+0,52+0,46+0,46+0,46+0,52+0
141,159065,https://sofifa.com/player/159065/ezequiel-lave...,E. Lavezzi,Ezequiel Iván Lavezzi,29,1985-05-03,173,75,Argentina,Paris Saint-Germain,...,61+1,60+1,60+1,60+1,61+1,55+1,49+1,49+1,49+1,55+1
217,178562,https://sofifa.com/player/178562/ever-banega/1...,E. Banega,Éver Maximiliano David Banega,26,1988-06-29,174,71,Argentina,Sevilla FC,...,74+0,77+0,77+0,77+0,74+0,70+0,67+0,67+0,67+0,70+0
229,192366,https://sofifa.com/player/192366/nicolas-otame...,N. Otamendi,Nicolás Hernán Otamendi,26,1988-02-12,183,75,Argentina,Valencia CF,...,71+0,72+0,72+0,72+0,71+0,75+0,80+0,80+0,80+0,75+0
283,179847,https://sofifa.com/player/179847/federico-fazi...,F. Fazio,Federico Julián Fazio,27,1987-03-17,195,91,Argentina,Tottenham Hotspur,...,69+0,75+0,75+0,75+0,69+0,74+0,80+0,80+0,80+0,74+0
285,188791,https://sofifa.com/player/188791/alberto-costa...,A. Costa,Alberto Facundo Costa,29,1985-01-09,176,75,Argentina,Spartak Moscow,...,75+0,77+0,77+0,77+0,75+0,74+0,70+0,70+0,70+0,74+0
287,196432,https://sofifa.com/player/196432/enzo-perez/15...,E. Pérez,Enzo Pérez,28,1986-02-22,177,77,Argentina,SL Benfica,...,79+0,79+0,79+0,79+0,79+0,78+0,76+0,76+0,76+0,78+0
289,186547,https://sofifa.com/player/186547/mateo-musacch...,M. Musacchio,Mateo Pablo Musacchio,23,1990-08-26,182,80,Argentina,Villarreal CF,...,73+0,76+0,76+0,76+0,73+0,77+0,79+0,79+0,79+0,77+0
291,191180,https://sofifa.com/player/191180/javier-pastor...,J. Pastore,Javier Matías Pastore,25,1989-06-20,187,78,Argentina,Paris Saint-Germain,...,66+1,68+1,68+1,68+1,66+1,60+1,55+1,55+1,55+1,60+1
303,190972,https://sofifa.com/player/190972/eduardo-salvi...,E. Salvio,Eduardo Antonio Salvio,23,1990-07-13,171,70,Argentina,SL Benfica,...,64+0,63+0,63+0,63+0,64+0,59+0,53+0,53+0,53+0,59+0
338,201862,https://sofifa.com/player/201862/marcos-rojo/1...,M. Rojo,Faustino Marcos Alberto Rojo,24,1990-03-20,186,82,Argentina,Manchester United,...,74+1,74+1,74+1,74+1,74+1,76+1,78+1,78+1,78+1,76+1
355,48745,https://sofifa.com/player/48745/fabricio-coloc...,F. Coloccini,Fabricio Coloccini,32,1982-01-22,184,83,Argentina,Newcastle United,...,73+1,73+1,73+1,73+1,73+1,76+1,78+1,78+1,78+1,76+1
360,134979,https://sofifa.com/player/134979/martin-demich...,M. Demichelis,Martín Gastón Demichelis,33,1980-12-20,184,78,Argentina,Manchester City,...,64+1,70+1,70+1,70+1,64+1,69+1,78+1,78+1,78+1,69+1
364,139062,https://sofifa.com/player/139062/willy-caballe...,W. Caballero,Wilfredo Daniel Caballero,32,1981-09-28,186,80,Argentina,Manchester City,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,142780,https://sofifa.com/player/142780/gonzalo-rodri...,G. Rodríguez,Gonzalo Javier Rodríguez,30,1984-04-10,182,79,Argentina,Fiorentina,...,71+0,76+0,76+0,76+0,71+0,75+0,79+0,79+0,79+0,75+0
407,170368,https://sofifa.com/player/170368/erik-lamela/1...,E. Lamela,Erik Lamela,22,1992-03-04,183,70,Argentina,Tottenham Hotspur,...,56+0,57+0,57+0,57+0,56+0,50+0,44+0,44+0,44+0,50+0
416,183899,https://sofifa.com/player/183899/pablo-piatti/...,P. Piatti,Pablo Daniel Piatti,25,1989-03-31,163,63,Argentina,Valencia CF,...,56+0,53+0,53+0,53+0,56+0,51+0,45+0,45+0,45+0,51+0
484,138123,https://sofifa.com/player/138123/esteban-cambi...,E. Cambiasso,Esteban Matías Cambiasso Delau,33,1980-08-18,177,78,Argentina,Leicester City,...,75+0,78+0,78+0,78+0,75+0,76+0,76+0,76+0,76+0,76+0
488,142708,https://sofifa.com/player/142708/diego-milito/...,D. Milito,Diego Alberto Milito,35,1979-06-12,183,78,Argentina,Racing Club,...,51+0,50+0,50+0,50+0,51+0,46+0,46+0,46+0,46+0,46+0
510,165501,https://sofifa.com/player/165501/nicolas-parej...,N. Pareja,Nicolás Martín Pareja,30,1984-01-19,181,74,Argentina,Sevilla FC,...,70+0,74+0,74+0,74+0,70+0,74+0,78+0,78+0,78+0,74+0
527,199151,https://sofifa.com/player/199151/juan-manuel-i...,J. Iturbe,Juan Manuel Iturbe Arévalo,21,1993-06-04,172,68,Argentina,Roma,...,54+0,51+0,51+0,51+0,54+0,47+0,40+0,40+0,40+0,47+0
539,193061,https://sofifa.com/player/193061/roberto-perey...,R. Pereyra,Roberto Pereyra,23,1991-01-07,184,78,Argentina,Juventus,...,73+0,73+0,73+0,73+0,73+0,71+0,67+0,67+0,67+0,71+0
546,179696,https://sofifa.com/player/179696/emiliano-insu...,E. Insua,Emiliano Adrián Insúa Zapata,25,1989-01-07,179,85,Argentina,Rayo Vallecano,...,76+0,76+0,76+0,76+0,76+0,77+0,77+0,77+0,77+0,77+0
579,173306,https://sofifa.com/player/173306/cristian-ansa...,C. Ansaldi,Cristian Daniel Ansaldi,27,1986-09-20,181,76,Argentina,Atlético Madrid,...,77+0,75+0,75+0,75+0,77+0,77+0,74+0,74+0,74+0,77+0
600,184252,https://sofifa.com/player/184252/lucas-pratto/...,L. Pratto,Lucas David Pratto,26,1988-06-04,188,82,Argentina,Vélez Sarsfield,...,57+0,62+0,62+0,62+0,57+0,54+0,52+0,52+0,52+0,54+0
615,110381,https://sofifa.com/player/110381/maximiliano-r...,M. Rodríguez,Maximiliano Rubén Rodríguez,33,1981-01-02,180,79,Argentina,Newell's Old Boys,...,63+0,64+0,64+0,64+0,63+0,58+0,56+0,56+0,56+0,58+0
621,123603,https://sofifa.com/player/123603/hugo-campagna...,H. Campagnaro,Hugo Armando Campagnaro,34,1980-06-27,181,85,Argentina,Inter,...,70+0,70+0,70+0,70+0,70+0,73+0,77+0,77+0,77+0,73+0
629,142938,https://sofifa.com/player/142938/german-denis/...,G. Denis,Germán Gustavo Denis,32,1981-09-10,182,87,Argentina,Atalanta,...,51+0,51+0,51+0,51+0,51+0,48+0,48+0,48+0,48+0,48+0
630,143121,https://sofifa.com/player/143121/jose-sosa/15/...,J. Sosa,José Ernesto Sosa,29,1985-06-19,181,77,Argentina,Beşiktaş JK,...,71+0,70+0,70+0,70+0,71+0,68+0,64+0,64+0,64+0,68+0
640,158963,https://sofifa.com/player/158963/lucas-biglia/...,L. Biglia,Lucas Rodrigo Biglia,28,1986-01-30,178,74,Argentina,Lazio,...,75+0,78+0,78+0,78+0,75+0,73+0,72+0,72+0,72+0,73+0
655,172114,https://sofifa.com/player/172114/diego-valeri/...,D. Valeri,Diego Hernán Váleri,28,1986-05-01,178,75,Argentina,Portland Timbers,...,56+0,60+0,60+0,60+0,56+0,51+0,47+0,47+0,47+0,51+0
661,176915,https://sofifa.com/player/176915/augusto-ferna...,A. Fernández,Augusto Matías Fernández,28,1986-04-10,177,71,Argentina,RC Celta,...,68+0,68+0,68+0,68+0,68+0,63+0,58+0,58+0,58+0,63+0
672,183893,https://sofifa.com/player/183893/claudio-yacob...,C. Yacob,Claudio Ariel Yacob,26,1987-07-18,181,73,Argentina,West Bromwich Albion,...,71+0,77+0,77+0,77+0,71+0,73+0,76+0,76+0,76+0,73+0
678,201399,https://sofifa.com/player/201399/mauro-icardi/...,M. Icardi,Mauro Emanuel Icardi Rivero,21,1993-02-19,181,75,Argentina,Inter,...,49+0,50+0,50+0,50+0,49+0,46+0,46+0,46+0,46+0,46+0
697,215316,https://sofifa.com/player/215316/geronimo-rull...,G. Rulli,Gerónimo Rulli,22,1992-05-20,189,80,Argentina,Real Sociedad,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,143076,https://sofifa.com/player/143076/alejandro-gom...,A. Gómez,Alejandro Darío Gómez,26,1988-02-15,165,68,Argentina,Atalanta,...,55+0,53+0,53+0,53+0,55+0,47+0,37+0,37+0,37+0,47+0
766,153177,https://sofifa.com/player/153177/mauro-zarate/...,M. Zárate,Mauro Matías Zárate,27,1987-03-18,176,76,Argentina,West Ham United,...,59+0,59+0,59+0,59+0,59+0,54+0,50+0,50+0,50+0,54+0
775,188042,https://sofifa.com/player/188042/matias-suarez...,M. Suárez,Matías Ezequiel Suárez,26,1988-05-09,176,70,Argentina,RSC Anderlecht,...,55+0,55+0,55+0,55+0,55+0,48+0,43+0,43+0,43+0,48+0
799,23461,https://sofifa.com/player/23461/walter-samuel/...,W. Samuel,Walter Adrián Samuel Luján,36,1978-03-23,184,81,Argentina,FC Basel 1893,...,60+0,67+0,67+0,67+0,60+0,66+0,76+0,76+0,76+0,66+0
827,138810,https://sofifa.com/player/138810/alejandro-dom...,A. Domínguez,Alejandro Damián Domínguez,33,1981-06-10,175,73,Argentina,Olympiacos CFP,...,56+0,57+0,57+0,57+0,56+0,50+0,48+0,48+0,48+0,50+0
829,142775,https://sofifa.com/player/142775/agustin-orion...,A. Orión,Agustín Ignacio Orión,33,1981-06-26,187,85,Argentina,Boca Juniors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN